# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c48b79f72c8c1f4cba330726f0bfab4660afefe5b02f57c16ab63b5c25a319502d65deca19890a3a4fa99c4f1a3dddbea6969e27376f91870972462b771c59d

test:
  secret_key_base: 47f87ae19350964fe71e18d29b67bab2d977f712bb4687d4a17be747eba803ab38592d0492ef55cda22c58831fbc36035478783f4782b0f5e62e0d4032490277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
