# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c64a897cb894e248c7826b65e85a7fa2700c2bcd46b4f77ad7f68fd7dd4dd3b96c251916f64a1df62f2c217053845ce984ab618b2da6a201d983e85fb327419

test:
  secret_key_base: 87233753d50ccb39707240c6269bfbf30ad15839ecd022a96bf039dffd79b7d42aa4c08a6abeaad97789779e6857c075cf3f47e81660e0f28bf1f4beb5f3e5e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
